///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Covid19DataResultsGlobalStatistics {
/*
{
  "currentConfirmedCount": 29607663,
  "confirmedCount": 96708872,
  "curedCount": 65030318,
  "deadCount": 2070891,
  "currentConfirmedIncr": 299317,
  "confirmedIncr": 469231,
  "curedIncr": 159033,
  "deadIncr": 10881,
  "yesterdayConfirmedCountIncr": 469228
} 
*/

  int currentConfirmedCount;
  int confirmedCount;
  int curedCount;
  int deadCount;
  int currentConfirmedIncr;
  int confirmedIncr;
  int curedIncr;
  int deadIncr;
  int yesterdayConfirmedCountIncr;

  Covid19DataResultsGlobalStatistics({
    this.currentConfirmedCount,
    this.confirmedCount,
    this.curedCount,
    this.deadCount,
    this.currentConfirmedIncr,
    this.confirmedIncr,
    this.curedIncr,
    this.deadIncr,
    this.yesterdayConfirmedCountIncr,
  });
  Covid19DataResultsGlobalStatistics.fromJson(Map<String, dynamic> json) {
    currentConfirmedCount = json["currentConfirmedCount"]?.toInt();
    confirmedCount = json["confirmedCount"]?.toInt();
    curedCount = json["curedCount"]?.toInt();
    deadCount = json["deadCount"]?.toInt();
    currentConfirmedIncr = json["currentConfirmedIncr"]?.toInt();
    confirmedIncr = json["confirmedIncr"]?.toInt();
    curedIncr = json["curedIncr"]?.toInt();
    deadIncr = json["deadIncr"]?.toInt();
    yesterdayConfirmedCountIncr = json["yesterdayConfirmedCountIncr"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["currentConfirmedCount"] = currentConfirmedCount;
    data["confirmedCount"] = confirmedCount;
    data["curedCount"] = curedCount;
    data["deadCount"] = deadCount;
    data["currentConfirmedIncr"] = currentConfirmedIncr;
    data["confirmedIncr"] = confirmedIncr;
    data["curedIncr"] = curedIncr;
    data["deadIncr"] = deadIncr;
    data["yesterdayConfirmedCountIncr"] = yesterdayConfirmedCountIncr;
    return data;
  }
}

class Covid19DataResults {
/*
{
  "currentConfirmedCount": 2458,
  "currentConfirmedIncr": 163,
  "confirmedCount": 99417,
  "confirmedIncr": 226,
  "suspectedCount": 4563,
  "suspectedIncr": 18,
  "curedCount": 92151,
  "curedIncr": 62,
  "deadCount": 4808,
  "deadIncr": 1,
  "seriousCount": 844,
  "seriousIncr": 25,
  "globalStatistics": {
    "currentConfirmedCount": 29607663,
    "confirmedCount": 96708872,
    "curedCount": 65030318,
    "deadCount": 2070891,
    "currentConfirmedIncr": 299317,
    "confirmedIncr": 469231,
    "curedIncr": 159033,
    "deadIncr": 10881,
    "yesterdayConfirmedCountIncr": 469228
  },
  "generalRemark": "",
  "remark1": "易感人群：人群普遍易感。老年人及有基础疾病者感染后病情较重，儿童及婴幼儿也有发病",
  "remark2": "潜伏期：一般为 3～7 天，最长不超过 14 天，潜伏期内可能存在传染性，其中无症状病例传染性非常罕见",
  "remark3": "宿主：野生动物，可能为中华菊头蝠",
  "remark4": "",
  "remark5": "",
  "note1": "病毒：SARS-CoV-2，其导致疾病命名 COVID-19",
  "note2": "传染源：新冠肺炎的患者。无症状感染者也可能成为传染源。",
  "note3": "传播途径：经呼吸道飞沫、接触传播是主要的传播途径。气溶胶传播和消化道等传播途径尚待明确。",
  "updateTime": 1611210601341
} 
*/

  int currentConfirmedCount;
  int currentConfirmedIncr;
  int confirmedCount;
  int confirmedIncr;
  int suspectedCount;
  int suspectedIncr;
  int curedCount;
  int curedIncr;
  int deadCount;
  int deadIncr;
  int seriousCount;
  int seriousIncr;
  Covid19DataResultsGlobalStatistics globalStatistics;
  String generalRemark;
  String remark1;
  String remark2;
  String remark3;
  String remark4;
  String remark5;
  String note1;
  String note2;
  String note3;
  int updateTime;

  Covid19DataResults({
    //现有确诊
    this.currentConfirmedCount,
    //新增确诊
    this.currentConfirmedIncr,
    //累计确诊
    this.confirmedCount,
    //新增累计确诊
    this.confirmedIncr,
    //境外输入总数
    this.suspectedCount,
    //新增境外输入
    this.suspectedIncr,
    //治愈总数
    this.curedCount,
    //治愈新增
    this.curedIncr,
    //死亡总数
    this.deadCount,
    //死亡新增
    this.deadIncr,
    //无症状总数
    this.seriousCount,
    //无症状新增
    this.seriousIncr,
    this.globalStatistics,
    this.generalRemark,
    this.remark1,
    this.remark2,
    this.remark3,
    this.remark4,
    this.remark5,
    this.note1,
    this.note2,
    this.note3,
    //更新时间
    this.updateTime,
  });
  Covid19DataResults.fromJson(Map<String, dynamic> json) {
    currentConfirmedCount = json["currentConfirmedCount"]?.toInt();
    currentConfirmedIncr = json["currentConfirmedIncr"]?.toInt();
    confirmedCount = json["confirmedCount"]?.toInt();
    confirmedIncr = json["confirmedIncr"]?.toInt();
    suspectedCount = json["suspectedCount"]?.toInt();
    suspectedIncr = json["suspectedIncr"]?.toInt();
    curedCount = json["curedCount"]?.toInt();
    curedIncr = json["curedIncr"]?.toInt();
    deadCount = json["deadCount"]?.toInt();
    deadIncr = json["deadIncr"]?.toInt();
    seriousCount = json["seriousCount"]?.toInt();
    seriousIncr = json["seriousIncr"]?.toInt();
    globalStatistics = (json["globalStatistics"] != null)
        ? Covid19DataResultsGlobalStatistics.fromJson(json["globalStatistics"])
        : null;
    generalRemark = json["generalRemark"]?.toString();
    remark1 = json["remark1"]?.toString();
    remark2 = json["remark2"]?.toString();
    remark3 = json["remark3"]?.toString();
    remark4 = json["remark4"]?.toString();
    remark5 = json["remark5"]?.toString();
    note1 = json["note1"]?.toString();
    note2 = json["note2"]?.toString();
    note3 = json["note3"]?.toString();
    updateTime = json["updateTime"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["currentConfirmedCount"] = currentConfirmedCount;
    data["currentConfirmedIncr"] = currentConfirmedIncr;
    data["confirmedCount"] = confirmedCount;
    data["confirmedIncr"] = confirmedIncr;
    data["suspectedCount"] = suspectedCount;
    data["suspectedIncr"] = suspectedIncr;
    data["curedCount"] = curedCount;
    data["curedIncr"] = curedIncr;
    data["deadCount"] = deadCount;
    data["deadIncr"] = deadIncr;
    data["seriousCount"] = seriousCount;
    data["seriousIncr"] = seriousIncr;
    if (globalStatistics != null) {
      data["globalStatistics"] = globalStatistics.toJson();
    }
    data["generalRemark"] = generalRemark;
    data["remark1"] = remark1;
    data["remark2"] = remark2;
    data["remark3"] = remark3;
    data["remark4"] = remark4;
    data["remark5"] = remark5;
    data["note1"] = note1;
    data["note2"] = note2;
    data["note3"] = note3;
    data["updateTime"] = updateTime;
    return data;
  }
}

class Covid19Data {
/*
{
  "results": [
    {
      "currentConfirmedCount": 2458,
      "currentConfirmedIncr": 163,
      "confirmedCount": 99417,
      "confirmedIncr": 226,
      "suspectedCount": 4563,
      "suspectedIncr": 18,
      "curedCount": 92151,
      "curedIncr": 62,
      "deadCount": 4808,
      "deadIncr": 1,
      "seriousCount": 844,
      "seriousIncr": 25,
      "globalStatistics": {
        "currentConfirmedCount": 29607663,
        "confirmedCount": 96708872,
        "curedCount": 65030318,
        "deadCount": 2070891,
        "currentConfirmedIncr": 299317,
        "confirmedIncr": 469231,
        "curedIncr": 159033,
        "deadIncr": 10881,
        "yesterdayConfirmedCountIncr": 469228
      },
      "generalRemark": "",
      "remark1": "易感人群：人群普遍易感。老年人及有基础疾病者感染后病情较重，儿童及婴幼儿也有发病",
      "remark2": "潜伏期：一般为 3～7 天，最长不超过 14 天，潜伏期内可能存在传染性，其中无症状病例传染性非常罕见",
      "remark3": "宿主：野生动物，可能为中华菊头蝠",
      "remark4": "",
      "remark5": "",
      "note1": "病毒：SARS-CoV-2，其导致疾病命名 COVID-19",
      "note2": "传染源：新冠肺炎的患者。无症状感染者也可能成为传染源。",
      "note3": "传播途径：经呼吸道飞沫、接触传播是主要的传播途径。气溶胶传播和消化道等传播途径尚待明确。",
      "updateTime": 1611210601341
    }
  ],
  "success": true
} 
*/

  List<Covid19DataResults> results;
  bool success;

  Covid19Data({
    this.results,
    this.success,
  });
  Covid19Data.fromJson(Map<String, dynamic> json) {
    if (json["results"] != null) {
      var v = json["results"];
      var arr0 = List<Covid19DataResults>();
      v.forEach((v) {
        arr0.add(Covid19DataResults.fromJson(v));
      });
      results = arr0;
    }
    success = json["success"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (results != null) {
      var v = results;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["results"] = arr0;
    }
    data["success"] = success;
    return data;
  }
}
