///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HotSearchDataNewslist {
/*
{
  "hotword": "袁姗姗预测自己最后一名成真",
  "hotwordnum": "3551689"
} 
*/

  String hotword;
  String hotwordnum;

  HotSearchDataNewslist({
    this.hotword,
    this.hotwordnum,
  });
  HotSearchDataNewslist.fromJson(Map<String, dynamic> json) {
    hotword = json["hotword"]?.toString();
    hotwordnum = json["hotwordnum"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["hotword"] = hotword;
    data["hotwordnum"] = hotwordnum;
    return data;
  }
}

class HotSearchData {
/*
{
  "code": 200,
  "msg": "success",
  "newslist": [
    {
      "hotword": "袁姗姗预测自己最后一名成真",
      "hotwordnum": "3551689"
    }
  ]
} 
*/

  int code;
  String msg;
  List<HotSearchDataNewslist> newslist;

  HotSearchData({
    this.code,
    this.msg,
    this.newslist,
  });
  HotSearchData.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    msg = json["msg"]?.toString();
    if (json["newslist"] != null) {
      var v = json["newslist"];
      var arr0 = List<HotSearchDataNewslist>();
      v.forEach((v) {
        arr0.add(HotSearchDataNewslist.fromJson(v));
      });
      newslist = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["msg"] = msg;
    if (newslist != null) {
      var v = newslist;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["newslist"] = arr0;
    }
    return data;
  }
}
