///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NewsDataNewslist {
/*
{
  "ctime": "2021-01-21 22:00:13",
  "title": "独家｜西安一幼儿园3岁女童身现29处针眼后续 亲属：师生卫生间独处8分钟，孩子出来后一直揉她的手",
  "description": "女童身上的针眼（央广网发 微博截图）央广网西安1月21日消息（记者舒隆焕 刘昱 见习记者周彤）近日，陕西西安莲湖区大兴郡幼儿园3岁女童身上现29处针眼，家长质疑孩子受到幼儿园老师伤害的事件引起广泛关注。",
  "picUrl": "http://p9.toutiaoimg.com/img/pgc-image/SMj6bvP4ISZCB1~tplv-tt-cs0:900:499.jpg",
  "url": "http://toutiao.com/group/6920171724902400519/",
  "source": "央广网"
} 
*/

  String ctime;
  String title;
  String description;
  String picUrl;
  String url;
  String source;

  NewsDataNewslist({
    this.ctime,
    this.title,
    this.description,
    this.picUrl,
    this.url,
    this.source,
  });
  NewsDataNewslist.fromJson(Map<String, dynamic> json) {
    ctime = json["ctime"]?.toString();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    picUrl = json["picUrl"]?.toString();
    url = json["url"]?.toString();
    source = json["source"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["ctime"] = ctime;
    data["title"] = title;
    data["description"] = description;
    data["picUrl"] = picUrl;
    data["url"] = url;
    data["source"] = source;
    return data;
  }
}

class NewsData {
/*
{
  "code": 200,
  "msg": "success",
  "newslist": [
    {
      "ctime": "2021-01-21 22:00:13",
      "title": "独家｜西安一幼儿园3岁女童身现29处针眼后续 亲属：师生卫生间独处8分钟，孩子出来后一直揉她的手",
      "description": "女童身上的针眼（央广网发 微博截图）央广网西安1月21日消息（记者舒隆焕 刘昱 见习记者周彤）近日，陕西西安莲湖区大兴郡幼儿园3岁女童身上现29处针眼，家长质疑孩子受到幼儿园老师伤害的事件引起广泛关注。",
      "picUrl": "http://p9.toutiaoimg.com/img/pgc-image/SMj6bvP4ISZCB1~tplv-tt-cs0:900:499.jpg",
      "url": "http://toutiao.com/group/6920171724902400519/",
      "source": "央广网"
    }
  ]
} 
*/

  int code;
  String msg;
  List<NewsDataNewslist> newslist;

  NewsData({
    this.code,
    this.msg,
    this.newslist,
  });
  NewsData.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    msg = json["msg"]?.toString();
    if (json["newslist"] != null) {
      var v = json["newslist"];
      var arr0 = List<NewsDataNewslist>();
      v.forEach((v) {
        arr0.add(NewsDataNewslist.fromJson(v));
      });
      newslist = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["msg"] = msg;
    if (newslist != null) {
      var v = newslist;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["newslist"] = arr0;
    }
    return data;
  }
}
